name: Compare

on: [push, pull_request]

jobs:
  gerber:
    name: Plot gerbers
    runs-on: ubuntu-latest
    container:
      image: setsoft/kicad_auto:ki7

    steps:
    - uses: actions/checkout@v3

    - name: Run KiBot
      run: | 
        kibot -c ./gerbers.kibot.yaml

    - name: Upload Gerber files
      uses: actions/upload-artifact@v3
      with: 
        name: Gerbers
        path: ./gerbers/

  compare:
    name: Compare to desired output
    runs-on: ubuntu-latest
    needs: gerber

    steps:
    - run: sudo apt install gerbv 
        
    - uses: actions/checkout@v3
      with:
        repository: 'brandtks/GerberRender'

    - uses: actions/download-artifact@v3
      with:
        name: Gerbers
        path: .

    - name: Render the image
      run: | 
        ./gerbrend -o *Edge_Cuts.gbr -f *F_Cu.gbr -b *B_Cu.gbr -m *F_Mask.gbr -n *B_Mask.gbr -s *F_Silkscreen.gbr -t *B_Silkscreen.gbr

#    - name: Compare ours against a photo
#      run: | 
#        compare -metric PSNR front-render.png ./photo/front.png front_difference.png
#        compare -metric PSNR back-render.png ./photo/back.png back_difference.png
  
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with: 
        name: Similiarity
        path: |
         ./front-render.png
         ./back-render.png
#         ./percentage.txt